apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
spec:
  type: NodePort

  selector:
    app: todo-api

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081

