name: Todo API CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:

      # --------------------------------
      # 1. Checkout
      # --------------------------------
      - name: Checkout
        uses: actions/checkout@v4


      # --------------------------------
      # 2. Docker Login
      # --------------------------------
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # --------------------------------
      # 3. Docker Build
      # --------------------------------
      - name: Build Docker Image
        shell: powershell
        run: |
          $IMAGE = "${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }}"

          docker build -t $IMAGE .


      # --------------------------------
      # 4. Docker Push
      # --------------------------------
      - name: Push Docker Image
        shell: powershell
        run: |
          $IMAGE = "${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }}"

          docker push $IMAGE


      # --------------------------------
      # 5. Kubernetes Deploy
      # --------------------------------
      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          $IMAGE = "${{ secrets.DOCKERHUB_USERNAME }}/todo-api:${{ github.sha }}"

          kubectl set image deployment/todo-api `
            todo-api=$IMAGE `
            -n todo


      # --------------------------------
      # 6. Rollout 완료 대기
      # --------------------------------
      - name: Wait for Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/todo-api -n todo


      # --------------------------------
      # 7. Deployment Status
      # --------------------------------
      - name: Check Kubernetes
        shell: powershell
        run: |
          kubectl get pods -n todo
          kubectl get service -n todo
